version: '3.8'

services:
  traveltalk:
    build: .
    container_name: traveltalk_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./temp_audio:/app/temp_audio
    restart: always
